resources:
  repositories:
    - repository: templates
      endpoint: github.com_luzmila1993
      type: github
      name: luzmila1993/templates
      trigger: none
    - repository: policy-policyname
      endpoint: github.com_luzmila1993
      type: github
      name: luzmila1993/policy-policyname
      trigger: none              

trigger:
- main

pool:
  name: Azure Pipelines

parameters:
- name: appOptions
  displayName: Application options
  type: object
  default:
    - name: 'api-apiname'
      secret: ["setdbparms-wwvbm"]
    - name: 'lib-libname'
      secret: []
- name: appPolicies
  displayName: Application Policies options
  type: object
  default:
    - policy-policyname
    
variables:
- template: variables.yml

stages:
- stage: DeployApplication
  displayName: Deploy Application
  jobs:
  - deployment: DeployArgo
    workspace:
      clean: all
    displayName: Deploy in ArgoCD
    environment: $(environmentValue)
    strategy:
      runOnce:
        preDeploy:
          steps:
          - template: ibm-gitops-pre-deploy.yml@templates
            parameters:
              appOptions: ${{ parameters.appOptions }}
              appPolicies: ${{ parameters.appPolicies }}
        deploy:
          steps:
          - template: ibm-gitops-deploy.yml@templates
